### ISSUE TITLE
How to best handle dimensions that dont match the names assumed?

### ISSUE THREAD

**Issue by mpiannucci** [abkfenris/xarray_fmrc#10]
Im currently working on getting FMRC views to work with my kerhcunked DBOFS dataset. From what I am reading, I am seeing that the `time` dimension needs to be named `time`, is that correct?

For these datasets, the time var is named `ocean_time`, but has a `standard_name` of `time`. Just wanted to ask what you think the best way of handling it is, I was trying to not modify the variable names if possible

Dataset: https://nextgen-dmac.s3.amazonaws.com/nos/nos.dbofs.fields.nc.zarr

**Comment by mpiannucci** [comment]
![Screenshot 2023-03-17 at 10 30 41 AM](https://user-images.githubusercontent.com/1832671/225934270-65026f99-1152-44c2-a721-c53bf47f9784.png)

**Comment by abkfenris** [comment]
Ok, I've got a PR (#11) that should be able to handle if the time dimension is named something different, and doesn't require `forecast_reference_time` to be baked into each dataset within the datatree. I need to update the docs to handle that.
